BBPATH .= ":${LAYERDIR}"

BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "meta-hadron"
BBFILE_PATTERN_meta-hadron = "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-hadron = "10"

LAYERSERIES_COMPAT_meta-hadron = "scarthgap"
LAYERDEPENDS_meta-hadron = "core tegra"
